name: Check

on:
  push:
    branches:
      - "main"
      - "vite-ssr"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "19.x"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Clean install
        run: pnpm i

      - name: Test
        run: pnpm run test

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
